#!/bin/bash
# AWStats Updater 1.3 (build 20150508)
# Copyright (C) 2011-2015  Daniel Rudolf <www.daniel-rudolf.de>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License only.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# See <http://www.gnu.org/licenses/> to receive a full-text-copy of
# the GNU General Public License.

APP_NAME="$(basename "$0")"
EXIT_CODE=0

BUILD="20150508"
VERSION="1.3"

# usage
function showUsage() {
	echo "Usage:"
	echo "	$APP_NAME [OPTION]... [--update] [--rebuild|--rebuild-all]"
}

# include debian config
AWSTATS_NICE=10
AWSTATS_LANG="en"
if [ -r "/etc/default/awstats" ]; then
	. "/etc/default/awstats"
fi

# parse options
WWW_PATH="/var/cache/awstats/www"
UPDATE="yes"
REBUILD="current"
VERBOSE=1

while [ $# -gt 0 ]; do
	if [ "$1" == "--www-path" ]; then
		if [ $# -lt 2 ]; then
			echo "$APP_NAME: Invalid \`--www-path': No path given" >&2
			showUsage
			exit 1
		fi

		WWW_PATH="$2"
		shift 2

	elif [ "${1:0:11}" == "--www-path=" ]; then
		WWW_PATH="${1:11}"
		if [[ "$WWW_PATH" =~ ^(\".*\"|\'.*\')$ ]]; then
			let "WWW_PATH_LENGTH = ${#WWW_PATH} - 2"
			WWW_PATH="${WWW_PATH:1:$WWW_PATH_LENGTH}"
		fi

		if [ -z "$WWW_PATH" ]; then
			echo "$APP_NAME: Invalid \`--www-path': No path given" >&2
			showUsage
			exit 1
		fi

		shift

	elif [ "$1" == "--update" ]; then
		UPDATE="yes"
		shift

	elif [ "$1" == "--no-update" ]; then
		UPDATE="no"
		shift

	elif [ "$1" == "--rebuild" ]; then
		REBUILD="current"
		shift

	elif [ "$1" == "--no-rebuild" ]; then
		REBUILD="no"
		shift

	elif [ "$1" == "--rebuild-all" ]; then
		REBUILD="all"
		shift

	elif [ "$1" == "--verbose" ]; then
		((VERBOSE++))
		shift

	elif [ "$1" == "--quiet" ]; then
		((VERBOSE--))
		shift

	elif [ "$1" == "--help" ]; then
		showUsage
		echo
		echo "Update AWStats database and/or generate HTML pages. By default, $APP_NAME"
		echo "updates the database (\`--update') and creates HTML pages (\`--rebuild')"
		echo "for the current month. You can create HTML pages for all historic data"
		echo "using \`--rebuild-all'."
		echo
		echo "Application options:"
		echo "  --[no-]update      update AWStats database"
		echo "  --[no-]rebuild     generate static HTML pages (current month only)"
		echo "  --rebuild-all      generate static HTML pages (all historic data)"
		echo "  --www-path=PATH    where to store the generated HTML pages?"
		echo "                     default: /var/cache/awstats/www"
		echo "  --verbose          increase verbosity"
		echo "  --quiet            decrease verbosity"
		echo
		echo "Help options:"
		echo "  --help             display this help and exit"
		echo "  --version          output version information and exit"
		echo
		echo "Please report bugs using the contact form at <http://www.daniel-rudolf.de/>"
		exit 0

	elif [ "$1" == "--version" ]; then
		echo "awstats-update $VERSION ($BUILD)"
		echo "Copyright (C) 2011-2015 Daniel Rudolf"
		echo "License GPLv3: GNU GPL version 3 only <http://gnu.org/licenses/gpl.html>."
		echo "This is free software: you are free to change and redistribute it."
		echo "There is NO WARRANTY, to the extent permitted by law."
		echo
		echo "Written by Daniel Rudolf <http://www.daniel-rudolf.de/>"
		exit 0

	else
		echo "$APP_NAME: Unknown option \`$1'" >&2
		showUsage
		exit 1
	fi
done

# nothing to do?
if [ "$UPDATE" == "no" ] && [ "$REBUILD" == "no" ]; then
	echo "$APP_NAME: You specified \`--no-update' and \`--no-rebuild'; do you really want to do nothing?" >&2
	exit 1
fi

# validate www path
if [ ! -e "$WWW_PATH" ]; then
	echo "$APP_NAME: Invalid \`--www-path': $WWW_PATH: No such file or directory" >&2
	exit 1
elif [ ! -d "$WWW_PATH" ]; then
	echo "$APP_NAME: Invalid \`--www-path': $WWW_PATH: Not a directory" >&2
	exit 1
fi

# you must run this as root
if [ "$(id -u)" -ne "0" ]; then
	echo "$APP_NAME: You must run this as \`root'" >&2
	exit 1
fi

# prepare fds according to verbosity
# verbosity -1: hide stdout and stderr
# verbosity 0: print stderr, hide stdout
[ "$VERBOSE" -le -1 ] && exec 2> /dev/null
[ "$VERBOSE" -le 0 ] && exec 1> /dev/null
[ "$VERBOSE" -gt 1 ] && exec 3>&1 || exec 3> /dev/null
[ "$VERBOSE" -gt 2 ] && exec 4>&1 || exec 4> /dev/null

# perform --update
if [ "$UPDATE" == "yes" ]; then
	echo "Performing update..."

	IFS=$'\n'; for FILE in /etc/awstats/awstats.*.*.conf; do
		if [ "$FILE" == "/etc/awstats/awstats.*.*.conf" ]; then
			echo "$APP_NAME: Unable to perform update: No config files found" >&2
			exit 1
		fi

		REGEX="^\/etc\/awstats\/awstats\.([^\.]+)\.(.+)\.conf$"
		if ! [[ "$FILE" =~ $REGEX ]]; then
			echo "$APP_NAME: Unable to perform update: Invalid config file \`$FILE'" >&2
			exit 1
		fi

		# get host and host type
		HOST_TYPE="$(echo "$FILE" | sed -r "s/$REGEX/\1/")"
		HOST="$(echo "$FILE" | sed -r "s/$REGEX/\2/")"

		# do it!
		echo "  - $HOST ($HOST_TYPE)"
		nice -n "$AWSTATS_NICE" \
			awstats -config="$HOST_TYPE.$HOST" -update \
				| sed -e 's/^ /  /' | sed -e 's/^/    /' >&4
		UPDATE_EXIT_CODE=$?

		if [ "$UPDATE_EXIT_CODE" -ne 0 ]; then
			echo "  ! $HOST ($HOST_TYPE) FAILED with exit code $UPDATE_EXIT_CODE"
			EXIT_CODE=1
		fi
	done
fi

# check exit code
if [ "$EXIT_CODE" -ne 0 ]; then
	exit "$EXIT_CODE"
fi

# AWStats pages
PAGES=( main alldomains allhosts lasthosts unknownip allemails lastemails allemailr lastemailr alllogins lastlogins allrobots lastrobots urldetail urlentry urlexit osdetail browserdetail unknownbrowser unknownos refererse refererpages keyphrases keywords errors404 )

# perform --rebuild
if [ "$REBUILD" == "current" ]; then
	# perform rebuild for the current month
	echo "Generating static HTML pages..."

	IFS=$'\n'; for FILE in /etc/awstats/awstats.*.*.conf; do
		if [ "$FILE" == "/etc/awstats/awstats.*.*.conf" ]; then
			echo "$APP_NAME: Unable to generate static HTML pages: No config files found" >&2
			exit 1
		fi

		REGEX="^\/etc\/awstats\/awstats\.([^\.]+)\.(.+)\.conf$"
		if ! [[ "$FILE" =~ $REGEX ]]; then
			echo "$APP_NAME: Unable to generate static HTML pages: Invalid config file \`$FILE'" >&2
			exit 1
		fi

		HOST_TYPE="$(echo "$FILE" | sed -r "s/$REGEX/\1/")"
		HOST="$(echo "$FILE" | sed -r "s/$REGEX/\2/")"

		# get current date
		MONTH="$(date +%m)"
		YEAR="$(date +%Y)"

		# let the user know what happens
		if [ "$VERBOSE" -eq 2 ]; then
			echo -n "  - $HOST ($HOST_TYPE): " >&3
		else
			echo "  - $HOST ($HOST_TYPE)"
		fi

		# are we at the beginning of a new month?
		# then we should parse the previous month once again
		REBUILD_ROUNDS=1
		if [ "$(date +%-d)" -eq 1 ]; then
			REBUILD_ROUNDS=2
		fi

		# generate static HTML pages
		REBUILD_EXIT_CODE=0
		while [ $REBUILD_ROUNDS -gt 0 ]; do
			# do we have any data?
			if [ ! -f "/var/lib/awstats/awstats$MONTH$YEAR.$HOST_TYPE.$HOST.txt" ]; then
				echo "    - $YEAR-$MONTH: no data; skipping..." >&4
				[ "$VERBOSE" -eq 2 ] && echo -n "$YEAR-$MONTH (no data) " >&3
			else
				# create directories, if necessary
				if [ ! -d "$WWW_PATH/$HOST_TYPE" ]; then
					mkdir "$WWW_PATH/$HOST_TYPE"
				fi
				if [ ! -d "$WWW_PATH/$HOST_TYPE/$HOST" ]; then
					mkdir "$WWW_PATH/$HOST_TYPE/$HOST"
				fi
				if [ ! -d "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR" ]; then
					mkdir "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR"
				fi

				# delete and re-create destination directory
				if [ -e "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH" ]; then
					rm -r "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH"
				fi
				mkdir "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH"

				# let the user know what happens
				echo -n "    - $YEAR-$MONTH: " >&4
				[ "$VERBOSE" -eq 2 ] && echo -n "$YEAR-$MONTH " >&3

				# generate static HTML pages
				ROUND_EXIT_CODE=0
				PAGE_INDEX=0
				PAGE_COUNT=${#PAGES[@]}
				while [ $PAGE_INDEX -lt $PAGE_COUNT ]; do
					PAGE=${PAGES[$PAGE_INDEX]}
					((PAGE_INDEX++))

					echo -n "$PAGE " >&4

					nice -n "$AWSTATS_NICE" \
						awstats -config="$HOST_TYPE.$HOST" -update \
							-output="$PAGE" -year="$YEAR" -month="$MONTH" \
							-staticlinks -lang="$AWSTATS_LANG" \
						> "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.$PAGE.html"
					PAGE_EXIT_CODE=$?

					if [ "$PAGE_EXIT_CODE" -ne 0 ]; then
						echo -n "[FAILED with exit code $PAGE_EXIT_CODE] " >&4
						ROUND_EXIT_CODE=1
						REBUILD_EXIT_CODE=1
						EXIT_CODE=1
					fi
				done

				# symlink index.html
				ln -s "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.main.html" "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/index.html"

				echo "" >&4
				[ "$ROUND_EXIT_CODE" -ne 0 ] && echo "    ! $YEAR-$MONTH FAILED" >&4
				[ "$ROUND_EXIT_CODE" -ne 0 ] && [ "$VERBOSE" -eq 2 ] && echo -n "[FAILED] " >&3
			fi

			# prepare next rebuild round
			((REBUILD_ROUNDS--))

			[ "${MONTH:0:1}" == "0" ] && MONTH="${MONTH:1}"
			((MONTH--))
			[ "${#MONTH}" -eq 1 ] && MONTH="0$MONTH"

			if [ $MONTH == "00" ]; then
				MONTH=12
				((YEAR--))
			fi
		done

		[ "$VERBOSE" -eq 2 ] && echo "" >&3
		[ "$REBUILD_EXIT_CODE" -ne 0 ] && echo "  ! $HOST ($HOST_TYPE) FAILED"
	done

# perform --rebuild-all
elif [ "$REBUILD" == "all" ]; then
	# collect rebuild data
	# actually this wouldn't be necessary, but AWStats database files aren't sorted at all
	# this is just for the sake of a nicer output...
	echo "Collecting rebuild data..."

	REBUILD_DATA=""
	IFS=$'\n'; for FILE in /var/lib/awstats/awstats*.*.*.txt; do
		if [ "$FILE" == "/var/lib/awstats/awstats*.*.*.txt" ]; then
			echo "$APP_NAME: Unable to collect rebuild data: No database files found" >&2
			exit 1
		fi

		REGEX="^\/var\/lib\/awstats\/awstats([0-9]{2})([0-9]{4})\.([^\.]+)\.(.+)\.txt$"
		if ! [[ "$FILE" =~ $REGEX ]]; then
			echo "$APP_NAME: Unable to collect rebuild data: Invalid database file \`$FILE'" >&2
			exit 1
		fi

		HOST_TYPE="$(echo "$FILE" | sed -r "s/$REGEX/\3/")"
		HOST="$(echo "$FILE" | sed -r "s/$REGEX/\4/")"

		YEAR="$(echo "$FILE" | sed -r "s/$REGEX/\2/")"
		MONTH="$(echo "$FILE" | sed -r "s/$REGEX/\1/")"

		REBUILD_DATA="$(echo "$REBUILD_DATA" ; echo "$HOST_TYPE/$HOST/$YEAR/$MONTH")"
	done

	REBUILD_DATA="$(echo "$REBUILD_DATA" | LC_ALL=C sort)"

	# perform rebuild...
	echo "Generating static HTML pages..."

	REBUILD_EXIT_CODE=0
	PREVIOUS_HOST_TYPE=""
	PREVIOUS_HOST=""
	IGNORE_HOST_TYPE=""
	IGNORE_HOST=""
	IFS=$'\n'; for DATA in $REBUILD_DATA; do
		HOST_TYPE="$(echo "$DATA" | cut -d '/' -f 1)"
		HOST="$(echo "$DATA" | cut -d '/' -f 2)"

		YEAR="$(echo "$DATA" | cut -d '/' -f 3)"
		MONTH="$(echo "$DATA" | cut -d '/' -f 4)"

		# something is wrong with this host; ignore it!
		if [ "$IGNORE_HOST_TYPE" == "$HOST_TYPE" ] && [ "$IGNORE_HOST" == "$HOST" ]; then
			continue
		fi

		# new host
		if [ "$PREVIOUS_HOST_TYPE" != "$HOST_TYPE" ] || [ "$PREVIOUS_HOST" != "$HOST" ]; then
			if [ -n "$PREVIOUS_HOST" ] && [ "$VERBOSE" -eq 2 ]; then
				if [ "$PREVIOUS_HOST_TYPE" != "$IGNORE_HOST_TYPE" ] || [ "$PREVIOUS_HOST" != "$IGNORE_HOST" ]; then
					echo "" >&3
				fi
			fi

			[ "$REBUILD_EXIT_CODE" -ne 0 ] && echo "  ! $PREVIOUS_HOST ($PREVIOUS_HOST_TYPE) FAILED"
			REBUILD_EXIT_CODE=0

			PREVIOUS_HOST_TYPE="$HOST_TYPE"
			PREVIOUS_HOST="$HOST"

			# check for AWStats config file
			if [ ! -f "/etc/awstats/awstats.$HOST_TYPE.$HOST.conf" ]; then
				echo "  - $HOST ($HOST_TYPE): config file not found; skipping..."
				IGNORE_HOST_TYPE="$HOST_TYPE"
				IGNORE_HOST="$HOST"
				continue
			fi

			# print current host
			if [ "$VERBOSE" -eq 2 ]; then
				echo -n "  - $HOST ($HOST_TYPE): " >&3
			else
				echo "  - $HOST ($HOST_TYPE)"
			fi
		fi

		# create directories, if necessary
		if [ ! -d "$WWW_PATH/$HOST_TYPE" ]; then
			mkdir "$WWW_PATH/$HOST_TYPE"
		fi
		if [ ! -d "$WWW_PATH/$HOST_TYPE/$HOST" ]; then
			mkdir "$WWW_PATH/$HOST_TYPE/$HOST"
		fi
		if [ ! -d "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR" ]; then
			mkdir "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR"
		fi

		# delete and re-create destination directory
		if [ -e "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH" ]; then
			rm -r "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH"
		fi
		mkdir "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH"

		# let the user know what happens
		echo -n "    - $YEAR-$MONTH: " >&4
		[ "$VERBOSE" -eq 2 ] && echo -n "$YEAR-$MONTH " >&3

		# generate static HTML pages
		ROUND_EXIT_CODE=0
		PAGE_INDEX=0
		PAGE_COUNT=${#PAGES[@]}
		while [ $PAGE_INDEX -lt $PAGE_COUNT ]; do
			PAGE=${PAGES[$PAGE_INDEX]}
			((PAGE_INDEX++))

			echo -n "$PAGE " >&4

			nice -n "$AWSTATS_NICE" \
				awstats -config="$HOST_TYPE.$HOST" -update \
					-output="$PAGE" -year="$YEAR" -month="$MONTH" \
					-staticlinks -lang="$AWSTATS_LANG" \
				> "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.$PAGE.html"
			PAGE_EXIT_CODE=$?

			if [ "$PAGE_EXIT_CODE" -ne 0 ]; then
				echo -n "[FAILED with exit code $PAGE_EXIT_CODE] " >&4
				ROUND_EXIT_CODE=1
				REBUILD_EXIT_CODE=1
				EXIT_CODE=1
			fi
		done

		# symlink index.html
		ln -s "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/awstats.$HOST_TYPE.$HOST.main.html" "$WWW_PATH/$HOST_TYPE/$HOST/$YEAR/$MONTH/index.html"

		echo "" >&4
		[ "$ROUND_EXIT_CODE" -ne 0 ] && echo "    ! $YEAR-$MONTH FAILED" >&4
		[ "$ROUND_EXIT_CODE" -ne 0 ] && [ "$VERBOSE" -eq 2 ] && echo -n "[FAILED] " >&3
	done

	[ -n "$PREVIOUS_HOST" ] && [ "$VERBOSE" -eq 2 ] && echo "" >&3
	[ "$REBUILD_EXIT_CODE" -ne 0 ] && echo "  ! $HOST ($HOST_TYPE) FAILED"
fi

# clean up
exec 3>&-
exec 4>&-

# exit
exit "$EXIT_CODE"
